server.port=${PORT:8080}

spring.application.name=ecommerce-app

logging.level.root=INFO
logging.level.com.ecommerce=DEBUG

# H2 Database - will work on Render
spring.datasource.url=jdbc:h2:file:/tmp/ecommerce_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=BuyoraSuperSecretKey1234567890BuyoraSuperSecretKey1234567890
jwt.expiration=86400000
